### ISSUE TITLE
get_image_signature out of bounds panic with certain kinds of images

### ISSUE THREAD

**Issue by gert7** [alt-text-org/image-match-rs#1]
I noticed several images causing an out of bounds panic in the `get_image_signature` function. I'm not sure what's so special about these images in particular that causes this error, as other images of the same width and height don't cause this problem. It also persists when converting from PNG to WEBP. I've attached some images that cause this problem when handled with the simagef CLI tool, which depends on image-match.

```
thread '<unnamed>' panicked at /home/gert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image-match-0.2.3/src/lib.rs:347:9:
index out of bounds: the len is 57 but the index is 18446744073709551615
stack backtrace:
   0:     0x55fcbad4a5a6 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55fcbad4a5a6 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fcbad4a5a6 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55fcbad4a5a6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fcbad76a00 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x55fcbad76a00 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x55fcbad473af - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x55fcbad4a384 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55fcbad4a384 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55fcbad4bc07 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x55fcbad4b969 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x55fcbad4c108 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x55fcbad4bfe2 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:659:13
  13:     0x55fcbad4aaa6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55fcbad4bd34 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x55fcbad746d5 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x55fcbad74912 - core::panicking::panic_bounds_check::h5aa5e8a957e001f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:208:5
  17:     0x55fcba8952d9 - image_match::pixel_average::{{closure}}::h722d11f74568673f
                               at /home/gert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image-match-0.2.3/src/lib.rs:347:9
  18:     0x55fcba88c8ea - core::iter::adapters::map::map_fold::{{closure}}::heedff0d92f9449cc
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/iter/adapters/map.rs:89:28
  19:     0x55fcba88fac5 - <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold::h7fa1741582d761f8
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/slice/iter/macros.rs:232:27
  20:     0x55fcba88aef8 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h4108b8b47a95493e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/iter/adapters/map.rs:129:9
  21:     0x55fcba89702a - <f32 as core::iter::traits::accum::Sum>::sum::h44f8bc6bcc2d2f0c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/iter/traits/accum.rs:106:17
  22:     0x55fcba88c2e7 - core::iter::traits::iterator::Iterator::sum::h4ba14a1b8f104568
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/iter/traits/iterator.rs:3642:9
  23:     0x55fcba8951eb - image_match::pixel_average::hb4b617c15652b4b4
                               at /home/gert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image-match-0.2.3/src/lib.rs:346:20
  24:     0x55fcba89442b - image_match::grid_averages::h6cd0e95f393a956d
                               at /home/gert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image-match-0.2.3/src/lib.rs:231:31
  25:     0x55fcba893079 - image_match::compute_from_gray::hdae111ba5f040a86
                               at /home/gert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image-match-0.2.3/src/lib.rs:82:20
  26:     0x55fcba85bbec - image_match::image::get_image_signature::he89c5e3a6a0b3d58
                               at /home/gert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/image-match-0.2.3/src/image.rs:27:5
  27:     0x55fcba803710 - simagef::signature_maker_loop::h0ea9207fe826444b
                               at /home/gert/projects/simagef/src/main.rs:49:41
  28:     0x55fcba8461f8 - simagef::main_signatures::{{closure}}::h928e5333e89ab675
                               at /home/gert/projects/simagef/src/main.rs:151:13
  29:     0x55fcba8008a6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1673223e12e95831
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:155:18
  30:     0x55fcba832c11 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h5caf9760a9e6e7de
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/mod.rs:529:17
  31:     0x55fcba7eb091 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4322027291b61447
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panic/unwind_safe.rs:272:9
  32:     0x55fcba806512 - std::panicking::try::do_call::h48891d38303a7adf
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
  33:     0x55fcba806abb - __rust_try
  34:     0x55fcba806251 - std::panicking::try::h647d3d7391d2428a
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
  35:     0x55fcba8314db - std::panic::catch_unwind::h840f7459987f1ff3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
  36:     0x55fcba8314db - std::thread::Builder::spawn_unchecked_::{{closure}}::h2e400ca4a080f320
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/thread/mod.rs:528:30
  37:     0x55fcba81594e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9b7526c4b978719d
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  38:     0x55fcbad50815 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  39:     0x55fcbad50815 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  40:     0x55fcbad50815 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  41:     0x75cd0bbe155a - <unknown>
  42:     0x75cd0bc5ea3c - <unknown>
  43:                0x0 - <unknown>
```

![Screenshot_20240410_183010](https://github.com/alt-text-org/image-match-rs/assets/294073/59a60e11-74a2-4661-b7cd-6dbcdd1c0987)
![Screenshot_20240320_223757](https://github.com/alt-text-org/image-match-rs/assets/294073/0d1c0a1d-7bb4-4782-ab0e-54377d105d83)
![Screenshot_20240313_204445](https://github.com/alt-text-org/image-match-rs/assets/294073/b239d71a-ab7e-4ba3-8575-2129442e4d66)

**Comment by hkolbeck** [comment]
Hi there, I'm afraid health issues have removed my ability to code and I will not be able to address this. If you or someone you know might be up to take the project over, I'd love to chat: hello@hannah.industries

**Comment by paulotten** [comment]
Reviewing https://github.com/alt-text-org/image-match-rs/commit/074bdf2821a5419d035c63c760dc4d2c7caaaebd#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759 what was line 347 of lib.rs now appears to be line 358: https://github.com/alt-text-org/image-match-rs/blob/main/src/lib.rs#L358

[Google informs me that log base 2 of 18446744073709551615 is 64.](https://www.google.com/search?q=log(18446744073709551615)%2Flog(2)). So my guess would be a 64 bit underflow.

`y as i32 + *delta_y` or `x as i32 + *delta_x` is probably resulting in a negative number. If was code reviewing this I would suggest promoting both `y` and `*delta_y` to `isize`, eg: `y as isize + *delta_y as isize`. This probably wouldn't be sufficient to prevent the underflow though. I suspect `pixel_average` is being called with `x` or `y` = `0`. This combined with the `-1` values in `PIXEL_DELTAS` looks like it could cause an underflow.

I'll see if I can debug the code and test this theory.

**Comment by str4d** [comment]
Looking at the crash:
```
index out of bounds: the len is 57 but the index is 18446744073709551615
```

The index is `0xffffffffffffffff`, or 2<sup>64</sup> - 1.

The crash occurs here:
https://github.com/alt-text-org/image-match-rs/blob/98971a53fb3b58347c52f9f2125709ccdca59cb8/src/lib.rs#L339-L351

`usize` is very likely `u64` on the given platform. If `x` or `y` is being set to 0 here, then for some of the `PIXEL_DELTAS` values, `y as i32 + *delta_y` or `x as i32 + *delta_x` will evaluate to `-1i32`, which when cast to `usize` will give `0xffffffffffffffff`.

`grid_points` doesn't produce `x = 0` or `y = 0`:
https://github.com/alt-text-org/image-match-rs/blob/98971a53fb3b58347c52f9f2125709ccdca59cb8/src/lib.rs#L200-L204

However, `pixel_average` is called with the point coordinates offset by some delta:
https://github.com/alt-text-org/image-match-rs/blob/98971a53fb3b58347c52f9f2125709ccdca59cb8/src/lib.rs#L227-L235

and `square_edge` can come from a user-provided function (`get_tuned_buffer_signature`):
https://github.com/alt-text-org/image-match-rs/blob/98971a53fb3b58347c52f9f2125709ccdca59cb8/src/lib.rs#L216-L224

**Comment by str4d** [comment]
(Hi @paulotten, you posted the same answer within seconds of me 😄)

The question now is what the correct behaviour at the image edges is, and in particular what the paper expects. I would presume either saturate (reuse the pixels adjacent to the edges of the image), or truncate (ignore the pixels that don't exist, and average over fewer pixels).

**Comment by paulotten** [comment]
Starting from https://github.com/gert7/simagef I changed this line in it's `Cargo.toml`

```
#image-match = { version = "0.2.3", features = ["img"] }
image-match = { path = "../image-match-rs", features = ["img"] }
```

Then I checked out `https://github.com/alt-text-org/image-match-rs` and added this as line 357 in `lib.rs`

```
println!("x={x}, y={y}");
```

Running `cargo run ../a.png ../b.png` where `a.png` and `b.png` are the image above with text "Tere! Mina olen Martin" I get the following output.

```
[...]
x=201, y=1
x=201, y=2
x=201, y=3
x=224, y=0
thread '<unnamed>' panicked at /home/paul/image-match/image-match-rs/src/lib.rs:359:9:
index out of bounds: the len is 136 but the index is 18446744073709551615
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[...]
x=226, y=8
x=226, y=9
x=226, y=10
x=24, y=0
thread '<unnamed>' panicked at /home/paul/image-match/image-match-rs/src/lib.rs:359:9:
index out of bounds: the len is 136 but the index is 18446744073709551615
thread 'main' panicked at src/main.rs:282:23:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

So @str4d and my theory seems to hold. `y` is underflowing.

I haven't convinced myself if the problem is in https://github.com/alt-text-org/image-match-rs or https://github.com/gert7/simagef yet.

**Comment by paulotten** [comment]
I've got a debugger running. The entry point for https://github.com/gert7/simagef/ in to https://github.com/alt-text-org/image-match-rs is here: https://github.com/gert7/simagef/blob/main/src/main.rs#L49, `get_image_signature`.

![image](https://github.com/alt-text-org/image-match-rs/assets/843079/2fb964c8-ebb5-4553-a2d7-8c2b84a7a3fe)

**Comment by str4d** [comment]
`image_match::image::get_image_signature` uses the following `average_square_width_fn`:
https://github.com/alt-text-org/image-match-rs/blob/98971a53fb3b58347c52f9f2125709ccdca59cb8/src/image.rs#L20-L25

So by construction it will return at least 1, and thus `square_edge` will always take on a value that can make some image underflow. Whether or not that happens depends on how the above function interacts with the scaling factors here that generate the grid:
https://github.com/alt-text-org/image-match-rs/blob/98971a53fb3b58347c52f9f2125709ccdca59cb8/src/lib.rs#L195-L197

**Comment by paulotten** [comment]
https://github.com/alt-text-org/image-match-rs/blob/main/src/lib.rs#L245

From debugger:
```
point_y = 1
delta_y = -1
square_edge = 1
```

So `point_y` + `delta_y` is our `0`, which leads to our underflow in `pixel_average`.

**Comment by paulotten** [comment]
(I'm possibly a step behind you still @str4d.)

![image](https://github.com/alt-text-org/image-match-rs/assets/843079/1dda95c9-b638-4524-8e2d-546499451654)

The `y` values in `points` which comes from `fn grid_points` look wrong.

The `x` values are 25, 50, 75, 100, 125, 150, 175, 200, 225. The image is 364 pixels wide but has a lot of white, empty space, so maybe that's correct after cropping.

The `y` values are 1, 2, 3, 4, 5, 6, 7, 8, 9. The image is 136 pixels high. These `y` values are way off.

**Comment by str4d** [comment]
Found a bug that I think is likely contributing: the grid points are not overlaying the intended part of the image, and `grid_averages` is being computed over parts of the image that were cropped.

https://github.com/alt-text-org/image-match-rs/blob/98971a53fb3b58347c52f9f2125709ccdca59cb8/src/lib.rs#L195-L207

The bounds after cropping are used to determine the number of points necessary to produce the desired grid, but then the actual grid point coordinates are not offset by the lower bounds. This means that the point coordinates are inherently close to the lower edges of the pixel source, and much more likely to underflow. I think this should instead be:
```rust
            points.insert(
                (x as i8, y as i8),
                (x * x_width + bounds.lower_x, y * y_width + bounds.lower_y),
            ); 
```

This doesn't solve the underflow issue, because if the image has nothing to crop the the lower bounds will be close to the origin.

**Comment by paulotten** [comment]
![crop](https://github.com/alt-text-org/image-match-rs/assets/843079/e59efa5b-dd38-42c2-97c2-20b07c300c52)

Ok, so the cropped image is supposed to be (within a few pixels) something like the red outline.

**Comment by paulotten** [comment]
>  but then the actual grid point coordinates are not offset by the lower bounds.

THIS.

We need to be adding the lower bound on lines 244 and 245.

edit: line 213 like you did works too. Probably a bit better.

**Comment by paulotten** [comment]
https://github.com/alt-text-org/image-match-rs/pull/2 created.

@str4d shall we both volunteer to be co-maintainers for this crate?

**Comment by hkolbeck** [comment]
That would work well for me, and I so appreciate both your work here 💜

**Comment by hkolbeck** [comment]
Another has been in touch via email. and I will see about adding y'all as maintainers. I'm also working to make sure a well known and trusted friend has GH org and backend cloud account ownership ASAP in case I am unable to pass things off.

**Comment by hkolbeck** [comment]
@str4d @paulotten apologies for the ping, but I hope you'll understand my haste in this.

**Comment by paulotten** [comment]
> @paulotten apologies for the ping, but I hope you'll understand my haste in this.

Sent you an email.
